version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:14.15.5
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v14.15.5/node-v14.15.5-linux-x64.tar.xz
            sudo tar -xvf node-v14.15.5-linux-x64.tar.xz
            sudo cp -r node-v14.15.5-linux-x64/{bin,include,lib,share} /usr/
            node --version => v14.15.5
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed warrie/udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user warrie/udagram-api-user
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend warrie/udagram-frontend:v2
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy warrie/udagram-reverseproxy
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u warrie -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push warrie/udagram-api-feed
            docker push warrie/udagram-api-user
            docker push warrie/udagram-frontend:v2
            docker push warrie/udagram-reverseproxy
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]